#!/usr/bin/env ruby
# frozen_string_literal: true

require 'cejo'

require 'gli'
require 'dry-container'


class App
  extend GLI::App

  def self.services
    container = Dry::Container.new
    container.register(:folders, Cejo::Services::Folders.new)
    container.register(:utils, Cejo::Services::Utils.new)
  end

  program_desc 'Debian automation and services utilities.'

  # version Cejo::VERSION

  subcommand_option_handling :normal
  arguments :strict

  desc 'Describe some switch here'
  switch [:s,:switch]

  desc 'Describe some flag here'
  default_value 'the default'
  arg_name 'The name of the argument'
  flag [:f,:flagname]

  desc 'Miscellaneous system operations front-end'
  arg_name 'Describe arguments to ops here'
  command :ops do |c|
    c.desc 'Describe a switch to ops'
    c.switch :s

    c.desc 'Describe a flag to ops'
    c.default_value 'default'
    c.flag :f

    utils = services.resolve(:utils)
    folders = services.resolve(:folders)

    c.desc 'Manage System Volume'
    c.arg '[up, down, toggle]'
    c.command :volume do |all|
      all.action do
        Cejo::Ops::Volume.new(utils, arguments.first).run
      end
    end

    c.desc 'Mirror user DATA partition folders to $HOME'
    c.arg '/folder/path/'
    c.command :homey do |all|
      all.action do
        Cejo::Ops::Homey.new(arguments.first).run
      end
    end

    c.desc 'Mirror Lar files in $HOME.'
    c.arg '/folder/path/'
    c.command :dots do |all|
      all.action do
        Cejo::Ops::Dots.new(utils, arguments.first).run
      end
    end

    c.desc 'Display System Hardware Information.'
    c.command :sysinfo do |all|
      all.action do
        Cejo::Ops::Sysinfo.new(utils, arguments.first).run
      end
    end

    c.desc 'Take a shot of the marvelous screen'
    c.arg '[full, partial]'
    c.command :screenshot do |all|
      all.action do
        Cejo::Ops::Screenshot.new(utils, arguments.first).run
      end
    end

    c.desc 'Manage System brightness.'
    c.arg '[up down]'
    c.command :brightness do |all|
      all.action do
        Cejo::Ops::Brightness.new(utils, arguments.first).run
      end
    end

    c.action do |global_options,options,args|

      # Your command logic here

      # If you have any errors, just raise them
      # raise "that command made no sense"

      puts "ops command ran"
    end
  end

  desc 'Manage System media features'
  arg_name 'Describe arguments to media here'
  command :media do |c|
    c.desc 'Get media pointed in url.'
    c.arg 'url'
    c.command :get do |all|
      all.action do
        Cejo::Media::Get.new(arguments).run
      end
    end

    c.desc 'Play file, random media in folder or with url.'
    c.arg '[url, /path/to/file]'
    c.command :play do |all|
      all.action do
        Cejo::Media::Play.new(arguments.first).run
      end
    end

    c.action do |global_options,options,args|
      puts "media command ran"
    end
  end

  desc 'Build Cool Projects.'
  arg_name 'Describe arguments to projects here'
  command :projects do |c|
    c.desc 'GNU Emacs Editor'
    c.command :emacs do |all|
      all.action do
        Cejo::Projects::Emacs.new(services)
      end
    end

    c.desc 'Suckless Terminal'
    c.command :st do |wip|
      wip.action do
        Cejo::Projects::St.new(services).run
      end
    end

    c.desc 'Suckless window manager'
    c.command :dwm do |wip|
      wip.action do
        Cejo::Projects::Dwm.new(services).run
      end
    end

    c.desc 'Ruby Programming language'
    c.command :ruby do |wip|
      wip.action do
        Cejo::Projects::Ruby.new(services).run
      end
    end

    c.action do |global_options,options,args|
      puts "projects command ran"
    end
  end

  desc 'A distro packager managers front-end just run it'
  arg_name 'Describe arguments to distro here'
  command :distro do |c|
    c.desc 'Install a Package from Repositories'
    c.arg 'arguments'
    c.command :install do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :install).run
      end
    end

    c.desc 'Remove One or More Installed Packages'
    c.arg 'arguments'
    c.command :autoremove do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :autoremove).run
      end
    end

    c.desc 'Remove One or More Installed Packages'
    c.arg 'arguments'
    c.command :remove do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :remove).run
      end
    end

    c.desc 'Find a Package'
    c.arg 'arguments'
    c.command :search do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :search).run
      end
    end

    c.desc 'Update Package Lists'
    c.arg 'arguments'
    c.command :update do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :update).run
      end
    end

    c.desc 'Upgrade Installed Packages'
    c.arg 'arguments'
    c.command :upgrade do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :upgrade).run
      end
    end

    c.desc 'Clean system residual packages dependencies'
    c.arg 'arguments'
    c.command :clean do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :clean).run
      end
    end

    c.desc 'Download package binary'
    c.arg 'arguments'
    c.command :download do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :download).run
      end
    end

    c.desc 'List installed packages'
    c.arg 'arguments'
    c.command :installed do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :installed).run
      end
    end

    c.desc 'View Info About a Specific Package'
    c.arg 'arguments'
    c.command :info do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :info).run
      end
    end

    c.desc 'Fix system issues'
    c.arg 'arguments'
    c.command :fix do |wip|
      wip.action do
        Cejo::Distro::Base.new(folders, utils, arguments, :fix).run
      end
    end

    c.action do |global_options,options,args|
      puts "distro command ran"
    end
  end

  desc 'Grab Floss Projects Repositories source'
  arg_name 'Describe arguments to floss here'
  command :floss do |c|
    utils = services.resolve(:utils)
    folders = services.resolve(:folders)

    c.desc 'Archive FLOSS Projects'
    c.command :archive do |wip|
      wip.action do
        Cejo::Floss::Core.new(folders, utils, :archive).run
      end
    end

    c.desc 'Grab FLOSS Projects'
    c.command :grab do |wip|
      wip.action do
        Cejo::Floss::Core.new(folders, utils, :grab).run
      end
    end

    c.action do |global_options,options,args|
      puts "floss command ran"
    end
  end

  pre do |global,command,options,args|
    # Pre logic here
    # Return true to proceed; false to abort and not call the
    # chosen command
    # Use skips_pre before a command to skip this block
    # on that command only
    true
  end

  post do |global,command,options,args|
    # Post logic here
    # Use skips_post before a command to skip this
    # block on that command only
  end

  on_error do |exception|
    # Error logic here
    # return false to skip default error handling
    true
  end
end

exit App.run(ARGV)
